# Copyright 2022 Google LLC.
# SPDX-License-Identifier: Apache-2.0

name: 'dbt_bq_spark'
version: '1.0.0'
config-version: 2
profile: 'dbt_bq_spark'
model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"




